In [2]:
import pandas as pd 
import numpy as np 

In [3]:
ds = pd.read_csv('C:/Users/Pratham/Downloads/Train_Data (1).csv')
ds.head()

duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsamesrvrate  dsthostdiffsrvrate  \
0              0       0    0  ...                0.06                0.06   
1              0       0    0  ...                0.45                0.04   
2              0       0    0  ...                1.00                0.00   
3              0       0    0  ...                1.00                0.00   
4              0       0    0  ...                0.01                0.08   

   dsthostsamesrcportrate  dsthostsrvdiffhostrate  dsthostserrorrate  \
0                    0.00                    0.00               0.00   
1                    0.00                    0.00               0.11   
2                    0.02                    0.03               0.00   
3                    0.00                    0.00               0.00   
4                    0.00                    0.00               0.00   

   dsthostsrvserrorrate  dsthostrerrorrate  dsthostsrvrerrorrate  lastflag  \
0                   0.0               1.00                   1.0        21   
1                   0.0               0.02                   0.0        18   
2                   0.0               0.00                   0.0        21   
3                   0.0               0.00                   0.0        21   
4                   0.0               1.00                   1.0        19   

   attack  
0       1  
1       0  
2       0  
3       0  
4       1  

[5 rows x 43 columns]

In [4]:
ds.shape

(86845, 43)

In [5]:
ds.describe

<bound method NDFrame.describe of        duration protocoltype      service flag  srcbytes  dstbytes  land  \
0             0          tcp  netbios_dgm  REJ         0         0     0   
1             0          tcp         smtp   SF      1239       400     0   
2             0          tcp         http   SF       222       945     0   
3             0          tcp         http   SF       235      1380     0   
4             0          tcp    uucp_path  REJ         0         0     0   
...         ...          ...          ...  ...       ...       ...   ...   
86840         0          tcp         http   SF       216       674     0   
86841         0          tcp         http   SF       368      1725     0   
86842        28          tcp          ftp   SF      1483      4152     0   
86843         0          tcp         smtp   SF      1679       385     0   
86844     11343          tcp       telnet   SF      3396     16694     0   

       wrongfragment  urgent  hot  ...  dsthostsamesr

In [6]:
ds.isnull().sum()

duration                  0
protocoltype              0
service                   0
flag                      0
srcbytes                  0
dstbytes                  0
land                      0
wrongfragment             0
urgent                    0
hot                       0
numfailedlogins           0
loggedin                  0
numcompromised            0
rootshell                 0
suattempted               0
numroot                   0
numfilecreations          0
numshells                 0
numaccessfiles            0
numoutboundcmds           0
ishostlogin               0
isguestlogin              0
count                     0
srvcount                  0
serrorrate                0
srvserrorrate             0
rerrorrate                0
srvrerrorrate             0
samesrvrate               0
diffsrvrate               0
srvdiffhostrate           0
dsthostcount              0
dsthostsrvcount           0
dsthostsamesrvrate        0
dsthostdiffsrvrate        0
dsthostsamesrcportra

In [7]:
ds.dtypes

duration                    int64
protocoltype               object
service                    object
flag                       object
srcbytes                    int64
dstbytes                    int64
land                        int64
wrongfragment               int64
urgent                      int64
hot                         int64
numfailedlogins             int64
loggedin                    int64
numcompromised              int64
rootshell                   int64
suattempted                 int64
numroot                     int64
numfilecreations            int64
numshells                   int64
numaccessfiles              int64
numoutboundcmds             int64
ishostlogin                 int64
isguestlogin                int64
count                       int64
srvcount                    int64
serrorrate                float64
srvserrorrate             float64
rerrorrate                float64
srvrerrorrate             float64
samesrvrate               float64
diffsrvrate   

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [9]:
categorical_vars = ds.select_dtypes(include = ['object']).columns
categorical_vars


Index(['protocoltype', 'service', 'flag'], dtype='object')

In [10]:
for col in categorical_vars:
    le = LabelEncoder()
    ds[col] = le.fit_transform(ds[col])
for col in categorical_vars:
    print (ds[col].head())

0    1
1    1
2    1
3    1
4    1
Name: protocoltype, dtype: int32
0    33
1    49
2    22
3    22
4    62
Name: service, dtype: int32
0    1
1    8
2    8
3    8
4    1
Name: flag, dtype: int32


In [11]:
y = ds['attack']
y.head()

0    1
1    0
2    0
3    0
4    1
Name: attack, dtype: int64

In [12]:
X = ds.drop(columns = 'attack', axis = 1) 
X.head()

duration  protocoltype  service  flag  srcbytes  dstbytes  land  \
0         0             1       33     1         0         0     0   
1         0             1       49     8      1239       400     0   
2         0             1       22     8       222       945     0   
3         0             1       22     8       235      1380     0   
4         0             1       62     1         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsrvcount  dsthostsamesrvrate  \
0              0       0    0  ...               15                0.06   
1              0       0    0  ...              116                0.45   
2              0       0    0  ...              255                1.00   
3              0       0    0  ...              255                1.00   
4              0       0    0  ...                3                0.01   

   dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
0                0.06                    0.00                    0.00   
1                0.04                    0.00                    0.00   
2                0.00                    0.02                    0.03   
3                0.00                    0.00                    0.00   
4                0.08                    0.00                    0.00   

   dsthostserrorrate  dsthostsrvserrorrate  dsthostrerrorrate  \
0               0.00                   0.0               1.00   
1               0.11                   0.0               0.02   
2               0.00                   0.0               0.00   
3               0.00                   0.0               0.00   
4               0.00                   0.0               1.00   

   dsthostsrvrerrorrate  lastflag  
0                   1.0        21  
1                   0.0        18  
2                   0.0        21  
3                   0.0        21  
4                   1.0        19  

[5 rows x 42 columns]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 10)
y_test.head()


84146    0
37807    1
28177    1
21166    0
72761    0
Name: attack, dtype: int64

In [14]:
lr = LogisticRegression(max_iter = 1000) 
lr.fit(X_train, y_train) 

c:\Pratham\New folder\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [15]:
lr_pred = lr.predict(X_test)
lr_pred

array([0, 1, 1, ..., 0, 1, 0], dtype=int64)

In [16]:
accuracy = accuracy_score (y_test, lr_pred) 
accuracy

0.9999616181776311

In [17]:
conf_matrix = confusion_matrix (y_test, lr_pred)
conf_matrix

array([[16194,     1],
       [    0,  9859]], dtype=int64)

In [18]:
class_report = classification_report(y_test, lr_pred)
class_report

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00     16195\n           1       1.00      1.00      1.00      9859\n\n    accuracy                           1.00     26054\n   macro avg       1.00      1.00      1.00     26054\nweighted avg       1.00      1.00      1.00     26054\n'

In [19]:
lr_pred2 = pd.DataFrame(lr_pred)
lr_pred2.to_csv('C:/Users/Pratham/Downloads/submit.csv', index = False)

In [24]:
df = pd.read_csv('C:/Users/Pratham/Downloads/Test_Data (1).csv') 

In [30]:
categorical_vars = df.select_dtypes(include = ['object']).columns
for col in categorical_vars:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
for col in categorical_vars:
    print (df[col].head())

0    1
1    1
2    1
3    1
4    1
Name: protocoltype, dtype: int32
0    31
1    22
2     9
3    55
4    16
Name: service, dtype: int32
0    1
1    8
2    4
3    4
4    4
Name: flag, dtype: int32


In [31]:
X_test1 = df
X_test1.head()

duration  protocoltype  service  flag  srcbytes  dstbytes  land  \
0         0             1       31     1         0         0     0   
1         0             1       22     8       199      1721     0   
2         0             1        9     4         0         0     0   
3         0             1       55     4         0         0     0   
4         0             1       16     4         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsrvcount  dsthostsamesrvrate  \
0              0       0    0  ...                7                0.03   
1              0       0    0  ...              255                1.00   
2              0       0    0  ...               14                0.05   
3              0       0    0  ...                2                0.01   
4              0       0    0  ...               16                0.06   

   dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
0                0.08                     0.0                     0.0   
1                0.00                     0.0                     0.0   
2                0.09                     0.0                     0.0   
3                0.09                     0.0                     0.0   
4                0.06                     0.0                     0.0   

   dsthostserrorrate  dsthostsrvserrorrate  dsthostrerrorrate  \
0                0.0                   0.0                1.0   
1                0.0                   0.0                0.0   
2                1.0                   1.0                0.0   
3                1.0                   1.0                0.0   
4                1.0                   1.0                0.0   

   dsthostsrvrerrorrate  lastflag  
0                   1.0        20  
1                   0.0        21  
2                   0.0        18  
3                   0.0        18  
4                   0.0        20  

[5 rows x 42 columns]

In [35]:
a = lr.predict(X_test1) 
a

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [44]:
b = pd.DataFrame(a)
b.rename (columns = {0 : 'attack'}, inplace = True) 
b.to_csv('C:/Users/Pratham/Downloads/suba.csv', index = False) 